#!/bin/sh

DGL=/tmp/dse-graph-loader-5.1.3/graphloader
if [ `hostname` = "node0" ]; then


   #Wait for DSE to be started
   dsetool status
   while [ $? -ne 0 ]; do
     sleep 5
     dsetool status
   done

   sleep 30
   cd resources/graph

   dse gremlin-console -e schema.groovy
   ${DGL} -graph fraud -address localhost fraud-mapping.groovy -inputpath data/
   dse gremlin-console -e edges.groovy

   #update graph keyspace replication
   sleep 5
   cqlsh localhost -f graphks.cql
   sleep 10

fi
