#!/bin/sh

cd resources/cql

echo "Waiting for DSE to settle"
sleep 240

cqlsh localhost -f create_schema.cql
#while [ $? -ne 0 ]; do
#  sleep 5
#  cqlsh localhost -f create_schema.cql
#done

#fix spark permissions
#chmod -R 777 /mnt/ephemeral/cassandra/spark/rdd
chown -R cassandra:cassandra /mnt/ephemeral/cassandra/spark
